### ISSUE TITLE
Use logic FK instead of DB FK

### ISSUE THREAD

**Issue by JandenMa** [willhmartin/Planner.Me#1]
> https://github.com/willhmartin/Planner.Me/blob/d4f75e0b8e9347d86fcff4222ebdc47a10f8da1f/db.sql#L12

Actually in real programming scenarios, we dont like DB FK, I know it is safer but always it would make the codes/logics complicated. So we usually use logic FK and control the logic by ourselves.

**Comment by willhmartin** [comment]
@JandenMa so remove the delete/cascade from the DB and write logic in server.js: delete an event and also fetch and delete each associated note. Is that what you mean?
I must still keep the event_id references right?

**Comment by JandenMa** [comment]
> @JandenMa so remove the delete/cascade from the DB and write logic in server.js: delete an event and also fetch and delete each associated note. Is that what you mean?
> I must still keep the event_id references right?

Yes you can store the event id but without fk constraint

**Comment by willhmartin** [comment]
Thanks, I’ll rewrite that.

**Comment by willhmartin** [comment]
The DB no longer has Foreign Key, logic for deleting notes with events now is in server.js
